[workspace]
members = ["gui/src-tauri"]
resolver = "2"

[workspace.package]
version = "1.0.0"
edition = "2021"
rust-version = "1.85"
authors = ["Brian McGillion <bmg.avoin@gmail.com>"]
license = "GPL-3.0"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
